### ISSUE TITLE
run test on test_ndi_validate in document_validation

### ISSUE THREAD

**Issue by stevevanhooser** [VH-Lab/NDI-matlab#155]

**Comment by stevevanhooser** [comment]
Hi Peter -

I merged this into the master branch. 

I am trying test_ndi_validate

and I get the error

Error using ndi_validate (line 88)
Java exception occurred:
java.lang.ClassCastException: com.ndi.EnumFormatValidator cannot be cast to
org.everit.json.schema.FormatValidator
	at com.ndi.Validator.performValidation(Validator.java:85)
	at com.ndi.Validator.getReport(Validator.java:64)







I thought it might be due to the class path order, so I tried running

javaaddpath('/Users/vanhoosr/Documents/MATLAB/tools/NDI-matlab/java/ndi-validator-java/jar/ndi-validator-java.jar')

so that it is the first in the class path but that also results in the same error. 


I also see that I have an extra program installed that has its own Java files on the static class path, so I moved that so they wouldn't be findable and they still seem to produce the same error. 

Can you please push the version of the validator that calls its own addpath close to where it used?

Here's my version info:

>> ver
-----------------------------------------------------------------------------------------------------
MATLAB Version: 9.8.0.1380330 (R2020a) Update 2
MATLAB License Number: 711743
Operating System: Mac OS X  Version: 10.14.6 Build: 18G6020 
Java Version: Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
-----------------------------------------------------------------------------------------------------

**Comment by stevevanhooser** [comment]
(we do validation differently now)
